// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbwZTwPH1VcjRKGpvSrgEZPJwXJK4U0lE',
    appId: '1:291452008264:android:3c14d62bb71aed8eb2a57d',
    messagingSenderId: '291452008264',
    projectId: 'bu-arts-passport',
    databaseURL: 'https://bu-arts-passport-default-rtdb.firebaseio.com',
    storageBucket: 'bu-arts-passport.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKpAIfitgSwl_sh_DIsdz-n8nZOZ31y3c',
    appId: '1:291452008264:ios:3ea6efe7baa82c76b2a57d',
    messagingSenderId: '291452008264',
    projectId: 'bu-arts-passport',
    databaseURL: 'https://bu-arts-passport-default-rtdb.firebaseio.com',
    storageBucket: 'bu-arts-passport.firebasestorage.app',
    iosBundleId: 'com.example.buPassport',
  );

}